### ISSUE TITLE
Remove binary builds from source repo

### ISSUE THREAD

**Issue by Yepoleb** [HUSKI3/Nimppt#1]
I noticed some executable files while reviewing your package. It's common practice to not store binary builds in your repository because git does not handle them well and your repository quickly grows in size and becomes slow to clone. The easiest way to ignore compiled files is to add their path to .gitignore. I saw you already uploaded builds in the release section which is the right way to distribute them.

**Comment by HUSKI3** [comment]
Got it, thank you! 
Patched in https://github.com/HUSKI3/Nimppt/commit/61f14d4f83f5ac9ccae9aaf3e2e44d71fb5d756b
